repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-git-author
        name: check git author
        entry: scripts/check-git-author.sh
        language: script
        pass_filenames: false
        stages: [pre-commit]

      - id: mypy
        name: mypy
        entry: mypy deckflow cli api
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

      - id: eslint
        name: eslint
        entry: bash -c 'cd web && npm run lint'
        language: system
        files: ^web/src/
        pass_filenames: false
